### ISSUE TITLE
pallas-index 模块开源吗

### ISSUE THREAD

**Issue by hadoop835** [vipshop/pallas#10]

**Comment by chembohuang** [comment]
感谢关注，pallas-index暂时还没开源的原因在于其技术栈相对复杂，用到了如定时任务的saturn，监听Binlog进行增量更新的rdp。计划今年第二季度左右会开源，到时会提供主要针对mysql数据源的：

- 标准的kafka消费(binglog的实时更新)；

- 全量导入(单表或表结构一致有全局唯一数值型ID的分库分表)

- 定时对账(db与es数据的查漏补缺)
